//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllotmentPlanner.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CropHarvest
    {
        public int cropId { get; set; }
        public System.DateTime earliestPlant { get; set; }
        public System.DateTime latestPlant { get; set; }
        public System.DateTime earliestHarvest { get; set; }
        public System.DateTime latestHarvest { get; set; }
        public Nullable<int> growthTime { get; set; }
    }
}
