//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllotmentPlanner.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crop_Requirements
    {
        public int cropId { get; set; }
        public bool birdNetting { get; set; }
        public bool slugPellets { get; set; }
        public bool Feed { get; set; }
        public bool Water { get; set; }
    }
}
