//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllotmentPlanner.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crop_Requirements
    {
        public int cropID { get; set; }
        public Nullable<bool> birdNetting { get; set; }
        public Nullable<bool> slugPellets { get; set; }
        public Nullable<bool> Feed { get; set; }
        public Nullable<bool> Water { get; set; }
    }
}
