//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllotmentPlanner.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class Crop
    {
        [Display(Name = "Crop Id")]
        public int cropId { get; set; }
        [Display(Name = "Crop Name")]
        public string cropName { get; set; }
        [Display(Name = "Seed Space required (sq in)")]
        public int cropSize { get; set; }
    }
}
