//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllotmentPlanner.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class GardenLocation
    {
        [Display(Name = "Garden Post Code")]
        public string postCode { get; set; }
        [Display(Name = "Garden Location Name")]
        public string Name { get; set; }
        [Display(Name = "Garden Location")]
        public string Owner { get; set; }
        public bool Active { get; set; }
    }
}
