//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllotmentPlanner.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planted
    {
        public int plantedId { get; set; }
        public int cropId { get; set; }
        public Nullable<System.DateTime> dateIn { get; set; }
        public Nullable<System.DateTime> dateOut { get; set; }
        public int gardenId { get; set; }
    }
}
