//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllotmentPlanner.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TendType
    {
        public int tendId { get; set; }
        public string tendName { get; set; }
    }
}
