//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllotmentPlanner.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class TendType
    {
        [Display(Name = "Tend Id")]
        public int tendId { get; set; }
        [Required(ErrorMessage = "Please Enter the Name of the Tend Action")]
        [Display(Name = "Tend Name")]
        public string tendName { get; set; }
        [Required(ErrorMessage = "Please Enter The frequency the tend needs to be applied")]
        [Display(Name = "Tend Frequency (days)")]
        public int tendFrequency { get; set; }
    }
}
